### ISSUE TITLE
503 error

### ISSUE THREAD

**Issue by Sheraff** [danzajdband/moviedb#24]
I just got this error when trying to request tons of things at once. Probably not a good idea on my part but still, throwing an error might not be the best response ;-)

/Users/Flo/Desktop/shows/server/node_modules/moviedb/lib/moviedb.js:41
    else throw res.error;
                  ^
Error: cannot GET /3/authentication/token/new?api_key=XXXXXXXXXXXXXXXXXXXXXX (503)
    at Response.toError (/Users/Flo/Desktop/shows/server/node_modules/moviedb/node_modules/superagent/lib/node/response.js:106:13)
    at Response.setStatusProperties (/Users/Flo/Desktop/shows/server/node_modules/moviedb/node_modules/superagent/lib/node/response.js:193:12)
    at new Response (/Users/Flo/Desktop/shows/server/node_modules/moviedb/node_modules/superagent/lib/node/response.js:42:8)
    at IncomingMessage.<anonymous> (/Users/Flo/Desktop/shows/server/node_modules/moviedb/node_modules/superagent/lib/node/index.js:935:22)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)

**Comment by danzajdband** [comment]
Sorry I missed this issue. 

The problem is with the authentication side. Check that you put a valid api_key.

**Comment by Sheraff** [comment]
It was a valid key, but probably got this response out of too many requests.

**Comment by danzajdband** [comment]
@Sheraff I closed it beacuse the lack of response but I'm glad to receive PR's if you want to improve the lib.
